### ISSUE TITLE
Captured pin is missing

### ISSUE THREAD

**Issue by moebis** [matthewlloyd/Voron-Parametric#1]
This version seems to be missing the captured pin and has a hole which I'm assuming is for inserting your own dowel or ping?

**Comment by matthewlloyd** [comment]
It's a Fusion 360 issue with the way joins work. Joins combine touching bodies, but the bodies affected depend on which are visible at the time the designer does the join. This isn't captured in the design history, so if you go back or change a parameter and roll forward, the resulting bodies can change. In this case the cut which makes the hole for the pin then deletes the pin too! The solution is to use separate components. I'll commit a fix in the next couple of hours.

If you're curious for more background - see https://forums.autodesk.com/t5/fusion-360-support/join-operation-during-extrude-joins-adjacent-bodies-unexpectedly/td-p/7034900
